name: asmita_flutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.1
  firebase_core: ^0.4.3+3
  firebase_analytics: ^5.0.11
  firebase_messaging: ^6.0.9
  animated_text_kit: ^2.0.0
  modal_progress_hud: ^0.1.3
  url_launcher: ^5.4.1
  intl: ^0.16.1
  flutter_plugin_pdf_viewer: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/nunitosans_black.ttf